config/routes.rb
RubyLinks::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :comments

  devise_for :users

  get '/links/tags_source'=>'links#tags_source'
  get '/links/get_images'=>'links#get_images'
  get '/links/jewel_it/:id'=>'links#jewel_it',:as=>:jewel_it
  get '/links/testing' => 'links#testing'
  get '/links/search_tags'=>'links#search_tags'
  get '/links/tag/:tag'=>'links#tag',:as=>:tag
  get '/links/search/:s' => 'links#search', as: :search

  resources :links do
    collection do
      get 'search'
    end
  end

  root :to => 'links#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
  attr_accessible :content,:link_id

  def belongs_to_user? user
    if user.nil?
      false
    else
      user.id==self.user.id
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  before_filter :authenticate_user!
  before_filter :comment_must_belong_to_user, :except =>[:new, :show, :index, :create]

  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @comment.user=current_user
    respond_to do |format|
      if @comment.save
        format.html {render "show", :layout=>false }
        format.json { render json: {:id=>@comment.id,:comment=>@comment.content,:user_email=>@comment.user.email,:time=>@comment.created_at.to_s(:long),:user_id=>@comment.user_id}, status: :created }
      else
        format.html 
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update

    unless params[:commit] == "Cancel"
      respond_to do |format|
        if @comment.update_attributes(params[:comment])
          format.html { redirect_to :back, notice: 'Comment was successfully updated.' }
          format.json { head :no_content }
          format.js
        else
          format.html { render action: "edit" }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
          format.html { redirect_to :back, notice: 'Comment was not updated.' }
          format.json { head :no_content }
          format.js
       end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  def edit_form
    @comment = Comment.find params[:id]
    render :layout => false
  end

  private
  def comment_must_belong_to_user
    @comment = Comment.find params[:id]
    redirect_to new_user_session_path, notice: "You do not have permission for this" unless @comment.user == current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
%div.comment{:id=>'comment_'+comment.id.to_s}
  %p.comment-content
    =comment.content
  %strong.comment-user
    =' - '+comment.user.email+' - '+comment.created_at.to_s(:long)
  - if comment.belongs_to_user? current_user
    &nbsp;
    %a.edit-comment.hidden{:href=>"#comment_#{comment.id}",:data=>{:id=>comment.id}}
      %i.icon-pencil.red
    %a.delete-comment.hidden{:href=>"#",:data=>{:id=>comment.id}}
      %i.icon-remove.red

app/views/comments/_form.html.haml
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

app/views/comments/edit_form.html.haml
=form_for(@comment, remote: true) do |f|
  = f.text_area :content, class: "rl-comment-field",:rows=>3
  %br
  = f.submit "Update", class: "btn btn-danger btn-mini"
  = f.submit "Cancel", class: "btn btn-danger cancel-cmt-update btn-mini"

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th Content
    %th Link
    %th User
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.content
      %td= comment.link
      %td= comment.user
      %td= link_to 'Show', comment
      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%div.comment{:id=>'comment_'+@comment.id.to_s}
  %p.comment-content
    =@comment.content
  %strong.comment-user
    =' - '+@comment.user.email+' - '+@comment.created_at.to_s(:long)
  - if @comment.belongs_to_user? current_user
    &nbsp;
    %a.edit-comment.hidden{:href=>"#comment_#{@comment.id}",:data=>{:id=>@comment.id}}
      %i.icon-pencil.red
    %a.delete-comment.hidden{:href=>"#",:data=>{:id=>@comment.id}}
      %i.icon-remove.red

app/views/comments/update.js.erb
$("#comment_<%=escape_javascript @comment.id.to_s %>").replaceWith("<%=escape_javascript render @comment %>");