config/routes.rb
RubyLinks::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :comments

  devise_for :users

  get '/links/tags_source'=>'links#tags_source'
  get '/links/get_images'=>'links#get_images'
  get '/links/jewel_it/:id'=>'links#jewel_it',:as=>:jewel_it
  get '/links/testing' => 'links#testing'
  get '/links/search_tags'=>'links#search_tags'
  get '/links/tag/:tag'=>'links#tag',:as=>:tag
  get '/links/search/:s' => 'links#search', as: :search

  resources :links do
    collection do
      get 'search'
    end
  end

  root :to => 'links#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :img, :title, :url,:user_id
  acts_as_taggable
  validates :url, :title, presence: true
  validates :url, uniqueness: true
  has_many :jewels, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user


  def jewel_it current_user
    if Jewel.jewel_count({:link=>self, :user=>current_user})==0
      Jewel.create(:link_id=>self.id,:user_id=>current_user.id)
      self.jewel = self.jewel+1
      self.save
    end
  end

  ##
  # Used when the user wants to remove his jewel from the link
  def un_jewel current_user
    if Jewel.jewel_count({:link=>self, :user=>current_user})==1
      Jewel.where("link_id = #{self.id} and user_id = #{current_user.id}").first.destroy
      self.jewel = self.jewel-1
      self.save
    end
  end

  ##
  # Returns Jewel if user has jeweled the link
  def jeweled_by? current_user
    self.jewels.where(user_id: current_user.id).first
  end

  def belongs_to_user? user = nil
    if user.nil?
      false
    else
      self.user == user
    end
  end


  def self.imgs_from_url url
    url.chomp! '/'
    agent = Mechanize.new
    page = agent.get(url)
    images = page.search("img")
    srcs=Array.new
    count=0
    images.each do |img|
      #puts img.attributes["src"]
      src=img.attributes["src"].value
      src=URI.join(url,src).to_s
      srcs << src
      count+=1
      if count==6
        break
      end
    end
    srcs
  end

  # searches records in locations table with the given criteria
  def self.search search_string = nil
    search_conditions = []
    if search_string
      columns = ["title", "description"] # what columns needs to be searched
      words = search_string.split(/\s+/)
      for word in words
        column_conditions = []
        for column in columns
          #search string sanitized
          column_conditions << ActiveRecord::Base.send(:sanitize_sql_array,[" lower(#{column}) like ?","%#{word.downcase}%"])
        end
        search_conditions << "(#{column_conditions.join(' or ')})"
      end
    end
    condition = []
    condition << "(#{search_conditions.join(' and ')})" if search_string
    # condition << "customer_id = #{customer.id}" if customer
    # condition << "user_id = #{user.id}" if user
    # condition << "records.created_at >= '#{start_time.beginning_of_day.to_formatted_s(:db)}'" if start_time and end_time
    # condition << "records.created_at <= '#{end_time.end_of_day.to_formatted_s(:db)}'" if start_time and end_time
    query = condition.join(' and ')
    # p query
    self.where(query) # sql injection attack must be checked
  end

  ##
  # returns youtube embed html if its a youtube video
  def youtube
    youtube_embed = '<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/VIDEO_ID" frameborder="0" allowfullscreen></iframe>'    
    if self.url =~ /.*http:\/\/(\w+\.)?youtube.com\/watch.*/
      self.url.match(/v=(\w+)/)
      return youtube_embed.gsub(/VIDEO_ID/, $1)  
    end
    return nil
  end
  
  ##
  # returns vimeo embed html if its a youtube video
  def vimeo
    vimeo_embed = "<iframe src=\"http:\/\/player.vimeo.com\/video\/VIDEO_ID\" width=\"640\" height=\"390\" frameborder=\"0\" webkitAllowFullScreen mozallowfullscreen allowFullScreen><\/iframe>"    
    if self.url =~ /.*http:\/\/(\w+\.)?vimeo.com\/(\d+).*/
      return vimeo_embed.gsub(/VIDEO_ID/, $2)  
    end
    return nil
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_filter :authenticate_user!, :except=> ["index","show","tag","tags_source","search_tags", "search","testing"]
  before_filter :link_must_belong_to_user, :only=> [:update, :destroy, :edit]


  def testing
  end

  # GET /links
  # GET /links.json
  def index
    @links = Link.order('created_at DESC').page(params[:page]).per(20)
    @title="All Links"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  def tag
    #tag=params[:tag] # this gave an error when tags like ruby 2.0 was used
    tag = URI.decode(request.url.split(/\//).last)
    @title=tag
    @links=Link.tagged_with(tag).order('created_at DESC').page(params[:page]).per(20)

    render :index
  end


  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
    @title = @link.title
    @comments=@link.comments.page(params[:page]).per(20)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @title = "Submit a Link"
    @link = Link.new
    @current_tags=""
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @title = "Edit Link"
    @current_tags=@link.tags.join(',')
  end

  def tags_source
      tags=Tag.all_tags
      respond_to do |format|
        #format.html
        format.json { render json: tags }
      end
  end

  def search_tags
    query=params[:q]
    results=Tag.search_tags(query).map(&:name)

    respond_to do |format|
      format.json { render json: {:query=>query,:results=>results,:count=>results.count} }
    end

  end

  def get_images
    url=params[:url]
    images=Link.imgs_from_url(url)
    respond_to do |format|
        #format.html
        format.json { render json: images }
      end
  end
  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])
    @link.tag_list=params["hidden-tags"]
    @link.user_id = current_user.id

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        @link.tag_list=params["hidden-tags"]
        @link.save
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def jewel_it
    @link=Link.find(params[:id])
    @link.jewel_it(current_user)
    respond_to do |format|
      format.json { render json: Jewel.jewel_count({:link=>@link}) }
      format.js
    end
  end

  def un_jewel
    @link=Link.find(params[:id])
    @link.un_jewel(current_user)
    respond_to do |format|
      format.json { render json: Jewel.jewel_count({:link=>@link}) }
      format.js
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_path, notice: "Link has been removed" }
      format.json { head :no_content }
    end
  end

  def search
    redirect_to({action: :index}, notice: "Search is empty") if params[:s].strip.empty?
    @links = Link.search(params[:s]).page(params[:page]).per(20)
    @title = "Result for #{params[:s]}"
    render :index
  end

  def link_must_belong_to_user
    @link = Link.find(params[:id])
    redirect_to(links_path, notice: "Oops! You can't do thothis if you did not create the link") unless @link.user == current_user
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_bread_crumb.html.haml
.row-fluid
  %ul.breadcrumb
    %li
      %a.with-icon( href="/")
        %i.icon-home
        %span.divider /
    %li= @title
    %li.pull-right
      = render partial: 'search_form'

app/views/links/_form.html.haml
%br
= form_for @link, :html=> {:class=>"form-horizontal"} do |f|
  - if @link.errors.any?
    #error_explanation
      %h2= "#{pluralize(@link.errors.count, "error")} prohibited this link from being saved:"
      %ul
        - @link.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :url,"URL",:class=>"control-label"
    .controls
      = f.text_field :url,:id=>"url",:class=>"input",:style=>"width: 40%;"
  .control-group
    = f.label :title,:class=>"control-label"
    .controls
      = f.text_field :title,:class=>"input",:style=>"width: 40%;"
  .control-group
    = f.label :description,:class=>"control-label"
    .controls
      = f.text_area :description,:class=>"pretty-look textarea"
  .control-group
    = f.label "Tags",:class=>"control-label"
    .controls
      = text_field_tag :tags,"",:class=>"tagManager input",:autocomplete=>"off",:style=>"width: 40%;"
      %p.help-block
        Seperate with comma. Maximum of 5 tags.
  %hr
  .control-group
    = f.label "Select an image or enter image URL",:class=>"control-label"
    .carousel.slide#thumb-carousel
      .carousel-inner
        .item.active
          %ul.thumbnails#images
    .controls
      = f.text_field :img, :class=>"control-label",:id=>"image-field", placeholder: "Image URL",:style=>"width: 40%;"

  .form-actions
    = link_to "Cancel", :back, :class=>"btn btn-danger"
    = f.submit 'Save',:class=>"btn btn-primary"

:javascript
  jQuery(".tagManager").tagsManager({
      prefilled: '#{@current_tags}',
      typeahead: true,
      maxTags: 5,
      typeaheadAjaxSource: '/links/tags_source'
    });

app/views/links/_link.html.haml
.link{:id=> link.id}
  %h1
    %span.link-num= "#"+link.id.to_s
    = link_to link.title, link_path(link.id)
  .row-fluid.link-description
    .span3
      -unless link.img.strip.empty?
        =image_tag link.img, class: 'link_image'
      -else
        =image_tag "link_64.png", class: 'link_image'
    .span9
      %p= raw(link.youtube) if link.youtube
      %p= raw(link.vimeo) if link.vimeo
      %p.small-font= link_to link.url, link.url
      %p= link.description
  .link-details
    %ul
      %li=link_to link.comments.count.to_s + " comments", link
      %li.jewel_count= Jewel.jewel_count({:link=>link}).to_s + ' Jewels'
      - if current_user
        -unless link.jeweled_by? current_user
          %li
            %span.btn.btn-danger.btn-mini.jewel-it{data:{ id: link.id}}
              Jewel It!
        -else
          %li
            %span.btn.btn-danger.btn-mini.un-jewel{data:{ id: link.id}}
              Un Jewel
      -if current_user
        %li= link_to "Comment", link, class: "btn btn-danger btn-mini"
      -else
        %li= link_to "Comment", new_user_session_path, class: "btn btn-danger btn-mini"
      %li= link_to "Edit", edit_link_path(link), class: "btn btn-danger btn-mini" if link.user == current_user
      %li.pull-right
        .tags
          - link.tags.each do |tag|
            =link_to tag.name,tag_path(tag.name)

app/views/links/_search_form.html.haml
= form_tag({action: :search}, method: :get, class: "form-inline pull-right") do
  .input-append
    = text_field_tag :s, params[:s], placeholder: "Type Somethin",class: "input", id:'appendedInputButton'
    = submit_tag "Search", class: "btn btn-danger"

app/views/links/_sidebar.html.haml
.well.sidebar-nav.rbl-sidebar
  %ul.nav.nav-list
    %li.nav-header= text_field_tag :query, nil, placeholder: "Tag Search",:id=>"tagsearch-field", autocomplete: "off"
  %ul.nav.nav-list#tag-search

app/views/links/edit.html.haml
=render partial: 'bread_crumb'

= render 'form'

app/views/links/index.html.haml
=render partial: 'bread_crumb'

#links= render @links

=paginate @links, theme: "bootstrap"

app/views/links/jewel_it.js.erb
$('#'+<%= @link.id %>).html('<%= escape_javascript(render(:partial=>"link",:locals=>{:link=>@link})) %>');

app/views/links/new.html.haml
=render partial: 'bread_crumb'

= render 'form'

app/views/links/show.html.haml
=render partial: 'bread_crumb'

%legend= @link.title
.row-fluid
  .span3
    -unless @link.img.strip.empty?
      =image_tag @link.img, class: 'link_image'
    -else
      =image_tag "link_64.png", class: 'link_image'
  .span9
    %p= raw(@link.youtube) if @link.youtube
    %p= raw(@link.vimeo) if @link.vimeo
    %p
      %b URL:
      = link_to @link.url, @link.url
    %p
      %b Description:
    %p= @link.description
    %p
      .tags
        - @link.tags.each do |tag|
          =link_to tag.name,tag_path(tag.name)
%br
- if current_user
  = link_to 'Add Comment', '#',:id=>'show-comment-field', class: "btn btn-danger"

- if @link.belongs_to_user? current_user
  = link_to 'Edit', edit_link_path(@link), class: "btn btn-danger"
  = link_to 'Delete', @link, method: :delete, class: "btn btn-danger"

%hr
#comments
  = render @comments
%br
#comment-field.hidden
  =form_tag comments_path,:method=>'POST',:id=>'comment-form' do
    = hidden_field_tag "comment[link_id]",@link.id
    = text_area_tag "comment[content]","",:rows=>3,:class=>'rl-comment-field'
    &nbsp;
    = submit_tag "Comment",:class=>'btn btn-inverse',:style=>"margin-top:-45px;",:id=>'submit-comment'


= paginate @comments, theme: "bootstrap" 

app/views/links/un_jewel.js.erb
$('#'+<%= @link.id %>).html('<%= escape_javascript(render(:partial=>"link",:locals=>{:link=>@link})) %>');