config/routes.rb
RubyLinks::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :comments

  devise_for :users

  get '/links/tags_source'=>'links#tags_source'
  get '/links/get_images'=>'links#get_images'
  get '/links/jewel_it/:id'=>'links#jewel_it',:as=>:jewel_it
  get '/links/testing' => 'links#testing'
  get '/links/search_tags'=>'links#search_tags'
  get '/links/tag/:tag'=>'links#tag',:as=>:tag
  get '/links/search/:s' => 'links#search', as: :search

  resources :links do
    collection do
      get 'search'
    end
  end

  root :to => 'links#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Ruby Links"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")
    = javascript_include_tag "application"
    = render partial: "links/google_analytics" if Rails.env == "production" # track logs only in production

  %body
    .top-nav
      .row
        %ul.top-nav-list
          -if !user_signed_in?
            %li
              = link_to "Login &nbsp;| ".html_safe,new_user_session_path
            %li 
              = link_to "Sign Up",new_user_registration_path
          -else
            %li
              %a{href: "/user/profile"}
                %i.icon-user
                = current_user.email
                &nbsp;|
            %li
              = link_to "Logout",destroy_user_session_path,:method=>"delete"
    .rl-header
      %a(href= '/')
        .logo
          = image_tag ('logo.png')

      = link_to "<i class='icon-link'></i> Add Link".html_safe,new_link_path,:class=>"btn btn-danger btn-large pull-right",:style=>"margin-top:10px;"
        

                

    .container-fluid(style="min-height:100%;")

      .row-fluid

        .span3
          =render 'links/sidebar'

        .span9
          -flash.each do |name, msg|
            %div{class: "alert alert-#{ name == :notice ? 'success' : 'warning'} "}
              %button.close{:type=>"button", :data=>{:dismiss=>"alert"}}x
              = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
          = yield

    %footer.main
      %p
        &copy; Ruby Links (Big Bang - Infinite)
        \|
        =link_to "Github", "http://github.com/codetribe/ruby_links"

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster

app/views/layouts/devise.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Ruby Links"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")
    = javascript_include_tag "application"

  %body
    .top-nav
      .row
        %ul.top-nav-list
          -if !user_signed_in?
            %li
              = link_to "Login",new_user_session_path
          -else
            %li
              %a{href: "/user/profile"}
                %i.icon-user
                = current_user.email
                | 
              %li
                = link_to "Logout",destroy_user_session_path,:method=>"delete"
    .rl-header
      %a(href= '/')
        .logo
          = image_tag ('logo.png')

    .container-fluid

      .row-fluid
        -flash.each do |name, msg|
          %div{class: "alert alert-#{ name == :notice ? 'success' : 'warning'} "}
            %button.close{:type=>"button", :data=>{:dismiss=>"alert"}}x
            = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

        = yield

      %footer.main
        %p &copy; Ruby Links 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster